# Generated by Django 5.1.1 on 2024-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_request_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='admin_id',
            field=models.CharField(default='1648265210', max_length=255),
        ),
    ]
